file:
    upload-dir: /Users/dius_/Documents/uploads
flyway:
    password: admin123
    schemas: rest_with_spring_boot_udemy
    url: jdbc:mysql://localhost:3306/
    user: root
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost/registeredbooksapi?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jackson:
        default-property-inclusion: NON_NULL
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB